# Generated by Django 3.1.6 on 2021-02-19 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(db_index=True, max_length=50, verbose_name='Актёр')),
            ],
            options={
                'verbose_name': 'Актёр',
                'verbose_name_plural': 'Актёры',
                'ordering': ['actor'],
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director', models.CharField(db_index=True, max_length=50, verbose_name='Режиссёр')),
            ],
            options={
                'verbose_name': 'Режиссёр',
                'verbose_name_plural': 'Режиссёры',
                'ordering': ['director'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(db_index=True, max_length=50, verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ['genre'],
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Фильм')),
                ('annotation', models.CharField(max_length=1000, verbose_name='Аннотация')),
                ('awards', models.CharField(max_length=1000, verbose_name='Награды')),
                ('release_year', models.IntegerField(verbose_name='Год релиза')),
                ('duration', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Продолжительность')),
                ('url', models.URLField(max_length=300, verbose_name='Ссылка')),
                ('actors', models.ManyToManyField(to='films.Actor', verbose_name='Актёры')),
                ('directors', models.ManyToManyField(to='films.Director', verbose_name='Режиссёры')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.genre', verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
                'ordering': ['title'],
            },
        ),
    ]
