# Generated by Django 3.1.6 on 2021-02-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='image',
            field=models.ImageField(null=True, upload_to='images/%Y/%m/%d/', verbose_name='Изображние'),
        ),
    ]
