# Generated by Django 3.1.6 on 2021-02-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_film_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='annotation',
            field=models.CharField(max_length=5000, verbose_name='Аннотация'),
        ),
        migrations.AlterField(
            model_name='film',
            name='url',
            field=models.URLField(max_length=500, verbose_name='Ссылка'),
        ),
    ]
